version: 2
updates:
	- package-ecosystem: "npm"
		directory: "/"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 10
		ignore:
			- dependency-name: "*"
				update-types: ["version-update:semver-major"]

	- package-ecosystem: "npm"
		directory: "/auth-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

	- package-ecosystem: "npm"
		directory: "/cart-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

	- package-ecosystem: "npm"
		directory: "/fulfillment-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

	- package-ecosystem: "npm"
		directory: "/gateway-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

	- package-ecosystem: "npm"
		directory: "/inventory-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

	- package-ecosystem: "npm"
		directory: "/order-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

	- package-ecosystem: "npm"
		directory: "/payment-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

	- package-ecosystem: "npm"
		directory: "/product-worker"
		schedule:
			interval: "weekly"
		open-pull-requests-limit: 5

